- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/postcreate.sh
- .vscode/settings.json
- README.md
- fhdw/modelling/base.py
- hello_world.py
- pyproject.toml
- setup.cfg
> (#1) add poetry project structure

- .github/workflows/publish.yml
- .github/workflows/pytest.yml
- fhdw/modelling/base.py
- fhdw/modelling/pycaret.py
- fhdw/tests/test_base.py
- pyproject.toml
> set up ci cd

- .github/workflows/README.md
- .github/workflows/lint-reusable.yml
- .github/workflows/lint.yml
- .github/workflows/publish.yml
- .github/workflows/pytest-reusable.yml
- .github/workflows/pytest.yml
- .vscode/tasks.json
- README.md
> (#8) update workflow input for used python version

- .devcontainer/devcontainer.json
- fhdw/modelling/base.py
- fhdw/modelling/pycaret.py
- pyproject.toml
> (#11) update docs

- .gitignore
- fhdw/modelling/pycaret.py
- fhdw/tests/test_pycaret.py
- poetry.lock
- pyproject.toml
> (#16) function to persist data locally

- fhdw/modelling/pycaret.py
- fhdw/tests/test_pycaret.py
- pyproject.toml
> (#20) persist experiment feature

- fhdw/modelling/pycaret.py
- fhdw/tests/test_pycaret.py
- pyproject.toml
> (#22) file extension for experiment on persistence

- fhdw/modelling/pycaret.py
> (#32) remove redundant `create_model`

- fhdw/modelling/pycaret.py
- fhdw/tests/test_pycaret.py
> (#30) convenience function: add stacked model

- fhdw/modelling/base.py
- fhdw/modelling/pycaret.py
- fhdw/tests/test_base.py
- fhdw/tests/test_pycaret.py
> (#41) remove obsolete validate function

- fhdw/modelling/pycaret.py
- pyproject.toml
> (#51) catch error for not supported estimator

- fhdw/modelling/preprocessing.py
- fhdw/tests/test_preprocessing.py
- pyproject.toml
> (#55) add preprocessing tools

- fhdw/modelling/preprocessing.py
- fhdw/modelling/pycaret.py
- fhdw/tests/test_pycaret.py
- pyproject.toml
> (#59) convenience function: allow kwargs for experiment

- .devcontainer/Dockerfile
- fhdw/modelling/base.py
- fhdw/tests/test_base.py
- poetry.lock
- pyproject.toml
> (#61) add optional seperator to experiment name function

- fhdw/modelling/evaluation.py
- fhdw/tests/test_evaluation.py
- fhdw/tests/test_pycaret.py
- pyproject.toml
> (#53) add evaluation module and plot

- fhdw/modelling/base.py
- pyproject.toml
> (#63) update docstring of experiment name function

- .devcontainer/devcontainer.json
- .gitignore
- fhdw/modelling/pycaret.py
- fhdw/tests/test_pycaret.py
> (#45) convenience func: check check min number of methods

- fhdw/modelling/pycaret.py
- fhdw/tests/test_pycaret.py
> (#58) option to provide a pre-defined experiment in convenience function

- fhdw/tests/test_pycaret.py
- pyproject.toml
> (#70) fix test failing when medel type is StackingRegressor

- fhdw/modelling/evaluation.py
- fhdw/modelling/tracking.py
- fhdw/tests/test_tracking.py
- pyproject.toml
> (#64) add metrics logging function for mlflow

- .devcontainer/devcontainer.json
- fhdw/modelling/pycaret.py
- pyproject.toml
> (#74) ensembes no longer return best models

- fhdw/modelling/pycaret.py
- pyproject.toml
> (#73) fix tune model: define optimization criteria

- fhdw/modelling/pycaret.py
- fhdw/tests/test_pycaret.py
- pyproject.toml
> (#38) lower tuning iterations for tests

- fhdw/modelling/pycaret.py
- pyproject.toml
> (#84) fix experiment name print

- fhdw/modelling/pycaret.py
- fhdw/tests/test_pycaret.py
- pyproject.toml
> (#75) add voting / blend model to convenience function

- fhdw/modelling/pycaret.py
- fhdw/tests/test_pycaret.py
> update input validation

- .devcontainer/devcontainer.json
- README.md
- docs/_toc.yml
- fhdw/modelling/base.py
- fhdw/modelling/evaluation.py
- fhdw/modelling/pycaret.py
- fhdw/modelling/tracking.py
> (#89) fix API docs by adapting to google styled docstrings

- fhdw/modelling/tracking.py
- fhdw/tests/test_tracking.py
> (#92) add prefix for logged metrics

- fhdw/modelling/evaluation.py
- fhdw/tests/test_evaluation.py
- pyproject.toml
> (#93) rename plot function for more plausible API

- fhdw/modelling/pycaret.py
- pyproject.toml
> (#103) add turbo argument in `automl`

- fhdw/modelling/preprocessing.py
- fhdw/tests/test_preprocessing.py
> (#107) add outlier removal

- fhdw/modelling/evaluation.py
- fhdw/tests/test_evaluation.py
- pyproject.toml
>  (#109) add warning to metrics function in case of negative values

- fhdw/modelling/evaluation.py
- pyproject.toml
> (#111) get_regression_metrics should accept lists

- README.md
- fhdw/modelling/evaluation.py
- fhdw/tests/test_evaluation.py
- pyproject.toml
> (#113) estimates plot with predictions by mulitple models

- fhdw/modelling/base.py
- fhdw/modelling/evaluation.py
- fhdw/modelling/preprocessing.py
- fhdw/modelling/pycaret.py
- fhdw/modelling/tracking.py
- fhdw/tests/test_evaluation.py
- pyproject.toml
> (#114) bump version

- fhdw/modelling/tracking.py
- fhdw/tests/test_tracking.py
- pyproject.toml
> (#117) avoid attempts of logging `None` values to mlflow

- docs/mlflow-pycaret-management.ipynb
- fhdw/modelling/pycaret.py
- fhdw/modelling/tracking.py
- fhdw/tests/test_pycaret.py
- fhdw/tests/test_tracking.py
- poetry.lock
- pyproject.toml
> (#120) update dependencies and docs

- fhdw/modelling/pycaret.py
> (#121) pycaret pipeline: add tag for framework identification

- fhdw/modelling/evaluation.py
> (#122) add index as label to identity plot

- .gitignore
- poetry.lock
- pyproject.toml
> (#126) raise mlflow version

- fhdw/modelling/evaluation.py
- fhdw/tests/test_evaluation.py
> (#96) add plot for train/test distribution comparison

- .devcontainer/devcontainer.json
- fhdw/modelling/base.py
> (#133) update parameter description

- poetry.lock
- pyproject.toml
> (#137) raise `pyarrow` version

- .gitignore
- fhdw/modelling/evaluation.py
- poetry.lock
- pyproject.toml
> (#132) improve residual plot with opacity and zero line

- fhdw/modelling/evaluation.py
> (#134) add labels to residual plot

- fhdw/modelling/pycaret.py
- pyproject.toml
> (#139) allow adding custom tags per experiment
